
## Using Standard Contrasts

### Example: Treatment (First) Contrasts

treatment.first(3)
treatment.first(3,intercept=TRUE)
calm.decode(treatment.first(3))
calm.decode(treatment.first(3,intercept=TRUE))

### Example: Treatment (Last) Contrasts

treatment.last(3)
treatment.last(3,intercept=TRUE)
calm.decode(treatment.last(3))
calm.decode(treatment.last(3,intercept=TRUE))

### Example: Deviation (First) Contrasts

deviation.first(3)
deviation.first(3,intercept=TRUE)
calm.decode(deviation.first(3))
calm.decode(deviation.first(3,intercept=TRUE))

### Example: Deviation (Last) Contrasts

deviation.last(3)
deviation.last(3,intercept=TRUE)
calm.decode(deviation.last(3))
calm.decode(deviation.last(3,intercept=TRUE))

### Example: Helmert (Forward) Contrasts

helmert.forward(3)
helmert.forward(3,intercept=TRUE)
calm.decode(helmert.forward(3))
calm.decode(helmert.forward(3,intercept=TRUE))

### Example: Helmert (Reverse) Contrasts

helmert.reverse(3)
helmert.reverse(3,intercept=TRUE)
calm.decode(helmert.reverse(3))
calm.decode(helmert.reverse(3,intercept=TRUE))

### Example: Repeated (Forward) Contrasts

repeated.forward(3)
repeated.forward(3,intercept=TRUE)
calm.decode(repeated.forward(3))
calm.decode(repeated.forward(3,intercept=TRUE))

### Example: Repeated (Reverse) Contrasts

repeated.reverse(3)
repeated.reverse(3,intercept=TRUE)
calm.decode(repeated.reverse(3))
calm.decode(repeated.reverse(3,intercept=TRUE))
